# ==========================================
# General Settings
# ==========================================
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g history-limit 100000
set -sg escape-time 10

bind X kill-session

setw -g mode-keys vi

# Visual mode selections (Vim style)
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi C-v send -X begin-selection \; send -X rectangle-toggle
bind-key -T copy-mode-vi V send -X select-line

# Yanking and clear behaviors
bind-key -T copy-mode-vi y send -X copy-selection-no-clear \; send -X clear-selection
bind-key -T copy-mode-vi Enter send -X copy-selection-no-clear \; send -X clear-selection
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-no-clear \; send-keys -X clear-selection
bind-key -T copy-mode-vi Escape send -X clear-selection
bind-key -T copy-mode-vi C-[ send -X clear-selection

# ==========================================
# Configuration Reload
# ==========================================
bind r source-file ~/.config/tmux/.tmux.conf \; display-message "Am dat reload la configgu de tmux!!"
