# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

# ==========================================
# Configuration Reload
# ==========================================
set -g @config_file "~/.config/tmux/tmux.conf"

bind r run-shell "tmux source-file '#{@config_file}'" \; display-message "Am dat reload la configgu de tmux din fisieru #{@config_file} !!"

# ==========================================
# General Settings
# ==========================================
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g history-limit 100000
set -sg escape-time 10
set -g default-terminal "$TERM"

#vreau pe alt+b ca-i mai ergonomic
unbind C-b
set-option -g prefix M-b

# Allow sending it to other apps by pressing it twice
bind-key M-b send-prefix

# Kill session shortcut
bind X kill-session

# Easier and faster switching between next/prev window
bind M-p previous-window
bind M-n next-window
bind b last-window



# ==========================================
# Vi Copy Mode Keybindings
# ==========================================
setw -g mode-keys vi

# Visual mode selections (Vim style)
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi C-v send -X begin-selection \; send -X rectangle-toggle
bind-key -T copy-mode-vi V send -X select-line

# Vim Viewport Positioning (zz, zt, zb) via sub-key table
bind-key -T copy-mode-vi z switch-client -T multi-z
bind-key -T multi-z z send -X scroll-middle
bind-key -T multi-z t send -X scroll-top
bind-key -T multi-z b send -X scroll-bottom

# Yanking and clear behaviors
bind-key -T copy-mode-vi y send -X copy-selection-no-clear \; send -X clear-selection
bind-key -T copy-mode-vi Enter send -X copy-selection-no-clear \; send -X clear-selection
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-no-clear \; send-keys -X clear-selection
bind-key -T copy-mode-vi Escape send -X clear-selection
bind-key -T copy-mode-vi C-[ send -X clear-selection

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

