git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers
  overrideGpg: true
gui:
      nerdFontsVersion: "3"
      showCommandLog: false



os:
   # For opening a directory in an editor
  openDirInEditor: "nvim"
