git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers
  # overrideGpg: true
commit:
  gpgsign: true
gui:
  nerdFontsVersion: "3"
  showCommandLog: false
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 4
  shrinkSidePanelsToContent: true
os:
  openDirInEditor: "nvim"
