git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers
gui:
      nerdFontsVersion: "3"
      showCommandLog: false
      expandFocusedSidePanel: true
      expandedSidePanelWeight: 4
      expandedFocusedSidePanelFitsContent: true
os:
  openDirInEditor: "nvim"
